export const USUARIO_REGISTRADO = 'USUARIO_REGISTRADO'
export const USUARIO_INICIOSESION_EXITO = 'USUARIO_INICIOSESION_EXITO'
export const USUARIO_INICIOSESION_FALLA = 'USUARIO_INICIOSESION_FALLA'
export const USUARIO_CERRAR_SESION = 'USUARIO_CERRAR_SESION'
